name: workflow for diplom project
on:
  release:
    types: [published]
#   push:
#     branches: [ master ]
#     tags:
#       - "*"
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    name : ci
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REP_API: api
          REP_MICR1: courses
          REP_MICR2: bcknd
          IMAGE_TAG: ${{ steps.vars.outputs.tag }}
        run: |
          $GITHUB_ENV
          docker build -t $ECR_REGISTRY/$REP_API:$IMAGE_TAG ./api
          docker push $ECR_REGISTRY/$REP_API:$IMAGE_TAG
          docker build -t $ECR_REGISTRY/$REP_MICR1:$IMAGE_TAG ./micr1
          docker push $ECR_REGISTRY/$REP_MICR1:$IMAGE_TAG
          docker build -t $ECR_REGISTRY/$REP_MICR2:$IMAGE_TAG ./micr2
          docker push $ECR_REGISTRY/$REP_MICR2:$IMAGE_TAG
  deploy:
    name: CD
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: go to workdir
        run: cd ./terraform
      - name: Terraform Init
        uses: rewindio/terraform-github-actions@master
        with:
          tf_actions_subcommand: init
      - name: Terraform apply
        uses: rewindio/terraform-github-actions@master
        with:
          tf_actions_subcommand: apply
          args: -var="tag_version=$IMAGE_TAG"
        env:
          IMAGE_TAG: ${{ steps.vars.outputs.tag }}
    
  
