name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REP_API: api
          REP_MICR1: micr1
          REP_MICR2: micr2
          IMAGE_TAG: vtest
        run: |
          docker build -t $ECR_REGISTRY/$REP_API:$IMAGE_TAG ./$REP_API
          docker push $ECR_REGISTRY/$REP_API:$IMAGE_TAG
          docker build -t $ECR_REGISTRY/$REP_MICR1:$IMAGE_TAG ./$REP_MICR1
          docker push $ECR_REGISTRY/$REP_MICR1:$IMAGE_TAG
          docker build -t $ECR_REGISTRY/$REP_MICR2:$IMAGE_TAG ./$REP_MICR2
          docker push $ECR_REGISTRY/$REP_MICR2:$IMAGE_TAG
