name: diplom project TMS
on: [push]
jobs:
  build:
    name : ci
    runs-on: self-hosted
    steps:
      - name: start ci notification 
        run: | 
          ls -la
          pwd
          whoami
